<?php
/**
 * DRUPAL 8 NER importer.
 * Copyright (C) 2017. Tarik Curto <centro.tarik@live.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 */

function ner_import_theme() {

    $theme['setup_page'] = [
        'variables' => [
            'links' => []
        ],
        'template' => 'setup'
    ];

    $theme['structure_processed_page'] = [
        'variables' => [
            'compressed_module_url' => '#',
            'property_field_map' => ''
        ],
        'template' => 'structure_processed'
    ];

    return $theme;
}